Repository founder-srm/Founders-website, pull requests merged in 2025-01, with the labels that each got.

#31 24 fix events writeup page UI fixes
  sanity.types.ts
  schema.json
  src/app/(home)/blog/page.tsx
  src/app/(home)/blog/posts/[slug]/page.tsx
  src/app/(home)/events/[slug]/page.tsx
  src/app/(home)/events/page.tsx
  src/app/(home)/events/writeup/[slug]/layout.tsx
  src/app/(home)/events/writeup/[slug]/page.tsx
  src/app/page.tsx
  src/app/robots.ts
  src/app/sitemap.ts
  src/components/footer.tsx
  src/components/navbar.tsx
  src/components/recent-events.tsx
  src/sanity/lib/queries.ts
  src/sanity/schemaTypes/eventType.ts
Labels: bug, enhancement, good first issue, help wanted

#32 Resend ADDED
  bun.lockb
  package.json
  src/app/(dashboard)/dashboard/upcoming/register/success/page.tsx
  src/app/api/send-ticket/route.ts
  src/components/RateLimitedButton.tsx
  src/components/email-templates/template.tsx
Labels: enhancement

#39 [ENHANCE} ImgBot config images
  public/FC-logo-short.png
  public/FC-logo1.png
  public/FC-logo2.jpeg
  public/fc-logo.png
  src/app/apple-icon.png
Labels: bug, enhancement, good first issue

#47 Form-and-registrations-fixes
  .gitignore
  src/app/(admin)/admin/layout.tsx
  src/app/(dashboard)/dashboard/upcoming/register/[slug]/multistep-typeform.tsx
  src/app/(dashboard)/dashboard/upcoming/register/[slug]/page.tsx
  src/app/(home)/upcoming/layout.tsx
  src/app/(home)/upcoming/more-info/[slug]/page.tsx
  src/app/(home)/upcoming/page.tsx
  src/components/banner.tsx
  src/components/sidebar/nav-user.tsx
  src/components/sidebar/sidebar-right.tsx
  src/components/theme/theme-toggle.tsx
  src/components/upcoming-card.tsx
  src/components/upcoming-featured.tsx
  src/components/upcoming-nav.tsx
Labels: enhancement, good first issue, help wanted
